export const LOCATION_FETCH_ADDRESS_FROM_COORDS_INIT =
  "LOCATION_FETCH_ADDRESS_FROM_COORDS_INIT";
export const LOCATION_FETCH_ADDRESS_FROM_COORDS_SUCCESS =
  "LOCATION_FETCH_ADDRESS_FROM_COORDS_SUCCESS";
export const LOCATION_FETCH_ADDRESS_FROM_COORDS_ERROR =
  "LOCATION_FETCH_ADDRESS_FROM_COORDS_ERROR";

export const LOCATION_FETCH_SUGGESTIONS_FROM_QUERY_INIT =
  "LOCATION_FETCH_SUGGESTIONS_FROM_QUERY_INIT";
export const LOCATION_FETCH_SUGGESTIONS_FROM_QUERY_SUCCESS =
  "LOCATION_FETCH_SUGGESTIONS_FROM_QUERY_SUCCESS";
export const LOCATION_FETCH_SUGGESTIONS_FROM_QUERY_ERROR =
  "LOCATION_FETCH_SUGGESTIONS_FROM_QUERY_ERROR";

export const LOCATION_FETCH_ADDRESS_FROM_SUGGESTION_INIT =
  "LOCATION_FETCH_ADDRESS_FROM_SUGGESTION_INIT";
export const LOCATION_FETCH_ADDRESS_FROM_SUGGESTION_SUCCESS =
  "LOCATION_FETCH_ADDRESS_FROM_SUGGESTION_SUCCESS";
export const LOCATION_FETCH_ADDRESS_FROM_SUGGESTION_ERROR =
  "LOCATION_FETCH_ADDRESS_FROM_SUGGESTION_ERROR";

export const LOCATION_SUGGESTIONS_RESET = "LOCATION_SUGGESTIONS_RESET";
